[version]
path = "src/dbt/adapters/database/__version__.py"

[build.targets.wheel]
packages = ["src/dbt"]
sources = ["src"]

[envs.default]
pre-install-commands = [
    "pip install -e ../dbt-adapters",
    "pip install -e ../dbt-tests-adapter",
]
dependencies = [
    "dbt-common @ git+https://github.com/dbt-labs/dbt-common.git",
    "dbt-core @ git+https://github.com/dbt-labs/dbt-core.git#subdirectory=core",
    "pytest>=7.0,<8.0",
]

[envs.default.scripts]
setup = [
    "pre-commit install",
    "cp -n test.env.example test.env",
]
code-quality = "pre-commit run --all-files"
unit-tests = "python -m pytest {args:tests/unit}"
integration-tests = "python -m pytest {args:tests/functional}"
docker-dev = [
    "docker build -f docker/dev.Dockerfile -t dbt-database-dev .",
    "docker run --rm -it --name dbt-database-dev -v $(pwd):/opt/code dbt-database-dev",
]

[envs.build]
detached = true
dependencies = [
    "wheel",
    "twine",
    "check-wheel-contents",
]

[envs.build.scripts]
check-all = [
    "- check-wheel",
    "- check-sdist",
]
check-wheel = [
    "twine check dist/*",
    "find ./dist/dbt_database-*.whl -maxdepth 1 -type f | xargs python -m pip install --force-reinstall --find-links=dist/",
    "pip freeze | grep dbt-database",
]
check-sdist = [
    "check-wheel-contents dist/*.whl --ignore W007,W008",
    "find ./dist/dbt_database-*.gz -maxdepth 1 -type f | xargs python -m pip install --force-reinstall --find-links=dist/",
    "pip freeze | grep dbt-database",
]

[envs.ci]
pre-install-commands = [
    "pip install -e ../dbt-adapters",
    "pip install -e ../dbt-tests-adapter",
]
dependencies = [
    "dbt-common @ git+https://github.com/dbt-labs/dbt-common.git",
    "dbt-core @ git+https://github.com/dbt-labs/dbt-core.git#subdirectory=core",
    "pytest>=7.0,<8.0",
]

[envs.ci.scripts]
unit-tests = "python -m pytest tests/unit"
integration-tests = "python -m pytest tests/functional"

[envs.cd]
pre-install-commands = []
dependencies = [
    "dbt-tests-adapter>=1.11.0,<2.0",
    "pytest>=7.0,<8.0",
]

[envs.cd.scripts]
unit-tests = "python -m pytest tests/unit"
integration-tests = "python -m pytest tests/functional"
